import { defineConfig } from 'vite-plus'

const isCI = Boolean(process.env['CI'])

export default defineConfig({
  lint: {
    ignorePatterns: ['dist/**', 'dist-bin/**', 'build/**', 'coverage/**'],
    plugins: ['unicorn', 'typescript', 'oxc', 'import', 'node', 'promise'],
    env: {
      node: true,
    },
    categories: {
      correctness: 'error',
      suspicious: 'error',
      restriction: 'off',
      pedantic: 'off',
      perf: 'warn',
      style: 'off',
      nursery: 'off',
    },
    options: {
      typeAware: true,
      typeCheck: true,
      denyWarnings: true,
      maxWarnings: 0,
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      eqeqeq: ['error', 'smart'],
      'import/no-cycle': 'error',
      'import/no-duplicates': 'error',
      'import/no-self-import': 'error',
      'no-await-in-loop': 'off',
      'no-caller': 'error',
      'no-console': ['error', { allow: ['error', 'log'] }],
      'no-constructor-return': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-loss-of-precision': 'error',
      'no-new-func': 'error',
      'no-proto': 'error',
      'no-prototype-builtins': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-shadow-restricted-names': 'error',
      'no-template-curly-in-string': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'promise/no-return-wrap': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/prefer-as-const': 'error',
      'unicorn/no-instanceof-array': 'error',
      'unicorn/no-typeof-undefined': 'error',
      'unicorn/prefer-array-flat-map': 'error',
      'unicorn/prefer-node-protocol': 'error',
      'unicorn/prefer-number-properties': 'error',
    },
    overrides: [
      {
        files: ['test/**/*.ts', '**/*.test.ts'],
        plugins: ['vitest'],
        env: {
          vitest: true,
        },
        rules: {
          'no-script-url': 'off',
          'vitest/expect-expect': 'off',
          'vitest/no-disabled-tests': 'error',
          'vitest/no-focused-tests': 'error',
        },
      },
    ],
  },
  fmt: {
    ignorePatterns: [
      'dist/**',
      'dist-bin/**',
      'build/**',
      'coverage/**',
      'bun.lock',
      '.semgrep/**',
    ],
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    singleQuote: true,
    jsxSingleQuote: true,
    semi: false,
    trailingComma: 'all',
    arrowParens: 'always',
    bracketSpacing: true,
    endOfLine: 'lf',
    insertFinalNewline: true,
    sortImports: true,
    sortPackageJson: true,
  },
  check: {
    fmt: true,
    lint: true,
  },
  test: {
    include: ['test/**/*.test.ts'],
    environment: 'node',
    // ローカルは agent レポーターで成功したテストのログを抑える。CI は既定の出力のまま。
    reporters: isCI ? ['default'] : ['agent'],
    silent: isCI ? false : 'passed-only',
    coverage: {
      provider: 'v8',
      include: ['src/**/*.ts'],
      exclude: ['src/server.ts', 'src/cli.ts'],
      reporter: ['text', 'lcov'],
      thresholds: {
        statements: 95,
        branches: 95,
        functions: 95,
        lines: 95,
      },
    },
  },
  staged: {
    '*': 'vp check --fix',
  },
})
